version: "3.3"

services:
  mariadb:
    image: mariadb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/provision/mysql/init/01-databases.sql:/docker-entrypoint-initdb.d/01-databases.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: azis

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass turbofolk
    ports:
      - '6379:6379'

  main:
    build:
      context: ./mainService
    ports:
      - 8080:8080
    depends_on:
      - "mariadb"
      - "redis"
    environment:
      SPRING_PROFILES_ACTIVE: deployment


  auth:
    build:
      context: ./authorizationService
    ports:
      - 8081:8081
    depends_on:
      - "mariadb"
    environment:
      SPRING_PROFILES_ACTIVE: deployment

  fridge:
    build:
      context: ./fridge
    ports:
      - 8082:8082
    depends_on:
      - "mariadb"
      - "redis"
    environment:
      SPRING_PROFILES_ACTIVE: deployment


