image: gradle:6.7-jdk11

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  SPRING_PROFILES_ACTIVE: ci

mainService-build:
  stage: build
  script:
    gradle --build-cache :main:assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build/
      - .gradle/

mainService-checkStyle:
  stage: staticAnalysis
  script:
    gradle :mainService:checkstyleMain :mainService:checkStyleTest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build/
      - .gradle/
  allow_failure: true

mainService-PMD:
  stage: staticAnalysis
  script:
    gradle :mainService:pmdMain :mainService:pmdTest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build/
      - .gradle/
  allow_failure: true

mainService-test:
  stage: test
  script:
    gradle :mainService:test
